/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialsRouteImport } from './routes/socials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeleteMyDataRouteImport } from './routes/delete-my-data'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as ImagesIndexRouteImport } from './routes/images/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'
import { Route as ImagesKeyRouteImport } from './routes/images/$key'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PortfolioProjectIdIndexRouteImport } from './routes/portfolio/$projectId/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardSocialsIndexRouteImport } from './routes/dashboard/socials/index'
import { Route as DashboardSkillsIndexRouteImport } from './routes/dashboard/skills/index'
import { Route as DashboardQuotesIndexRouteImport } from './routes/dashboard/quotes/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardImagesIndexRouteImport } from './routes/dashboard/images/index'
import { Route as DashboardBlogsIndexRouteImport } from './routes/dashboard/blogs/index'
import { Route as DashboardBillboardsIndexRouteImport } from './routes/dashboard/billboards/index'
import { Route as DashboardSocialsSocialIdRouteImport } from './routes/dashboard/socials/$socialId'
import { Route as DashboardQuotesQuoteIdRouteImport } from './routes/dashboard/quotes/$quoteId'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardBlogsSlugRouteImport } from './routes/dashboard/blogs/$slug'
import { Route as DashboardBillboardsBillboardIdRouteImport } from './routes/dashboard/billboards/$billboardId'

const SocialsRoute = SocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteMyDataRoute = DeleteMyDataRouteImport.update({
  id: '/delete-my-data',
  path: '/delete-my-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesKeyRoute = ImagesKeyRouteImport.update({
  id: '/images/$key',
  path: '/images/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectIdIndexRoute = PortfolioProjectIdIndexRouteImport.update({
  id: '/portfolio/$projectId/',
  path: '/portfolio/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSocialsIndexRoute = DashboardSocialsIndexRouteImport.update({
  id: '/socials/',
  path: '/socials/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSkillsIndexRoute = DashboardSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardQuotesIndexRoute = DashboardQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImagesIndexRoute = DashboardImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogsIndexRoute = DashboardBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillboardsIndexRoute =
  DashboardBillboardsIndexRouteImport.update({
    id: '/billboards/',
    path: '/billboards/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSocialsSocialIdRoute =
  DashboardSocialsSocialIdRouteImport.update({
    id: '/socials/$socialId',
    path: '/socials/$socialId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardQuotesQuoteIdRoute = DashboardQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBlogsSlugRoute = DashboardBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillboardsBillboardIdRoute =
  DashboardBillboardsBillboardIdRouteImport.update({
    id: '/billboards/$billboardId',
    path: '/billboards/$billboardId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delete-my-data': typeof DeleteMyDataRoute
  '/login': typeof LoginRoute
  '/socials': typeof SocialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/images/$key': typeof ImagesKeyRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/images': typeof ImagesIndexRoute
  '/legal': typeof LegalIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/dashboard/billboards/$billboardId': typeof DashboardBillboardsBillboardIdRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/quotes/$quoteId': typeof DashboardQuotesQuoteIdRoute
  '/dashboard/socials/$socialId': typeof DashboardSocialsSocialIdRoute
  '/dashboard/billboards': typeof DashboardBillboardsIndexRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/images': typeof DashboardImagesIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/quotes': typeof DashboardQuotesIndexRoute
  '/dashboard/skills': typeof DashboardSkillsIndexRoute
  '/dashboard/socials': typeof DashboardSocialsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delete-my-data': typeof DeleteMyDataRoute
  '/login': typeof LoginRoute
  '/socials': typeof SocialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/images/$key': typeof ImagesKeyRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/images': typeof ImagesIndexRoute
  '/legal': typeof LegalIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/dashboard/billboards/$billboardId': typeof DashboardBillboardsBillboardIdRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/quotes/$quoteId': typeof DashboardQuotesQuoteIdRoute
  '/dashboard/socials/$socialId': typeof DashboardSocialsSocialIdRoute
  '/dashboard/billboards': typeof DashboardBillboardsIndexRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/images': typeof DashboardImagesIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/quotes': typeof DashboardQuotesIndexRoute
  '/dashboard/skills': typeof DashboardSkillsIndexRoute
  '/dashboard/socials': typeof DashboardSocialsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delete-my-data': typeof DeleteMyDataRoute
  '/login': typeof LoginRoute
  '/socials': typeof SocialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/images/$key': typeof ImagesKeyRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/dashboard/billboards/$billboardId': typeof DashboardBillboardsBillboardIdRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/quotes/$quoteId': typeof DashboardQuotesQuoteIdRoute
  '/dashboard/socials/$socialId': typeof DashboardSocialsSocialIdRoute
  '/dashboard/billboards/': typeof DashboardBillboardsIndexRoute
  '/dashboard/blogs/': typeof DashboardBlogsIndexRoute
  '/dashboard/images/': typeof DashboardImagesIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/quotes/': typeof DashboardQuotesIndexRoute
  '/dashboard/skills/': typeof DashboardSkillsIndexRoute
  '/dashboard/socials/': typeof DashboardSocialsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/portfolio/$projectId/': typeof PortfolioProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/404'
    | '/about'
    | '/contact'
    | '/delete-my-data'
    | '/login'
    | '/socials'
    | '/blog/$slug'
    | '/images/$key'
    | '/legal/$slug'
    | '/blog'
    | '/dashboard/'
    | '/images'
    | '/legal'
    | '/portfolio'
    | '/dashboard/billboards/$billboardId'
    | '/dashboard/blogs/$slug'
    | '/dashboard/projects/$projectId'
    | '/dashboard/quotes/$quoteId'
    | '/dashboard/socials/$socialId'
    | '/dashboard/billboards'
    | '/dashboard/blogs'
    | '/dashboard/images'
    | '/dashboard/projects'
    | '/dashboard/quotes'
    | '/dashboard/skills'
    | '/dashboard/socials'
    | '/dashboard/users'
    | '/portfolio/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/delete-my-data'
    | '/login'
    | '/socials'
    | '/blog/$slug'
    | '/images/$key'
    | '/legal/$slug'
    | '/blog'
    | '/dashboard'
    | '/images'
    | '/legal'
    | '/portfolio'
    | '/dashboard/billboards/$billboardId'
    | '/dashboard/blogs/$slug'
    | '/dashboard/projects/$projectId'
    | '/dashboard/quotes/$quoteId'
    | '/dashboard/socials/$socialId'
    | '/dashboard/billboards'
    | '/dashboard/blogs'
    | '/dashboard/images'
    | '/dashboard/projects'
    | '/dashboard/quotes'
    | '/dashboard/skills'
    | '/dashboard/socials'
    | '/dashboard/users'
    | '/portfolio/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/404'
    | '/about'
    | '/contact'
    | '/delete-my-data'
    | '/login'
    | '/socials'
    | '/blog/$slug'
    | '/images/$key'
    | '/legal/$slug'
    | '/blog/'
    | '/dashboard/'
    | '/images/'
    | '/legal/'
    | '/portfolio/'
    | '/dashboard/billboards/$billboardId'
    | '/dashboard/blogs/$slug'
    | '/dashboard/projects/$projectId'
    | '/dashboard/quotes/$quoteId'
    | '/dashboard/socials/$socialId'
    | '/dashboard/billboards/'
    | '/dashboard/blogs/'
    | '/dashboard/images/'
    | '/dashboard/projects/'
    | '/dashboard/quotes/'
    | '/dashboard/skills/'
    | '/dashboard/socials/'
    | '/dashboard/users/'
    | '/portfolio/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DeleteMyDataRoute: typeof DeleteMyDataRoute
  LoginRoute: typeof LoginRoute
  SocialsRoute: typeof SocialsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ImagesKeyRoute: typeof ImagesKeyRoute
  LegalSlugRoute: typeof LegalSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PortfolioProjectIdIndexRoute: typeof PortfolioProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/socials': {
      id: '/socials'
      path: '/socials'
      fullPath: '/socials'
      preLoaderRoute: typeof SocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-my-data': {
      id: '/delete-my-data'
      path: '/delete-my-data'
      fullPath: '/delete-my-data'
      preLoaderRoute: typeof DeleteMyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$key': {
      id: '/images/$key'
      path: '/images/$key'
      fullPath: '/images/$key'
      preLoaderRoute: typeof ImagesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$projectId/': {
      id: '/portfolio/$projectId/'
      path: '/portfolio/$projectId'
      fullPath: '/portfolio/$projectId'
      preLoaderRoute: typeof PortfolioProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/socials/': {
      id: '/dashboard/socials/'
      path: '/socials'
      fullPath: '/dashboard/socials'
      preLoaderRoute: typeof DashboardSocialsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/skills/': {
      id: '/dashboard/skills/'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quotes/': {
      id: '/dashboard/quotes/'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/images/': {
      id: '/dashboard/images/'
      path: '/images'
      fullPath: '/dashboard/images'
      preLoaderRoute: typeof DashboardImagesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blogs/': {
      id: '/dashboard/blogs/'
      path: '/blogs'
      fullPath: '/dashboard/blogs'
      preLoaderRoute: typeof DashboardBlogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billboards/': {
      id: '/dashboard/billboards/'
      path: '/billboards'
      fullPath: '/dashboard/billboards'
      preLoaderRoute: typeof DashboardBillboardsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/socials/$socialId': {
      id: '/dashboard/socials/$socialId'
      path: '/socials/$socialId'
      fullPath: '/dashboard/socials/$socialId'
      preLoaderRoute: typeof DashboardSocialsSocialIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quotes/$quoteId': {
      id: '/dashboard/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/dashboard/quotes/$quoteId'
      preLoaderRoute: typeof DashboardQuotesQuoteIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blogs/$slug': {
      id: '/dashboard/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/dashboard/blogs/$slug'
      preLoaderRoute: typeof DashboardBlogsSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billboards/$billboardId': {
      id: '/dashboard/billboards/$billboardId'
      path: '/billboards/$billboardId'
      fullPath: '/dashboard/billboards/$billboardId'
      preLoaderRoute: typeof DashboardBillboardsBillboardIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillboardsBillboardIdRoute: typeof DashboardBillboardsBillboardIdRoute
  DashboardBlogsSlugRoute: typeof DashboardBlogsSlugRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardQuotesQuoteIdRoute: typeof DashboardQuotesQuoteIdRoute
  DashboardSocialsSocialIdRoute: typeof DashboardSocialsSocialIdRoute
  DashboardBillboardsIndexRoute: typeof DashboardBillboardsIndexRoute
  DashboardBlogsIndexRoute: typeof DashboardBlogsIndexRoute
  DashboardImagesIndexRoute: typeof DashboardImagesIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardQuotesIndexRoute: typeof DashboardQuotesIndexRoute
  DashboardSkillsIndexRoute: typeof DashboardSkillsIndexRoute
  DashboardSocialsIndexRoute: typeof DashboardSocialsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillboardsBillboardIdRoute: DashboardBillboardsBillboardIdRoute,
  DashboardBlogsSlugRoute: DashboardBlogsSlugRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardQuotesQuoteIdRoute: DashboardQuotesQuoteIdRoute,
  DashboardSocialsSocialIdRoute: DashboardSocialsSocialIdRoute,
  DashboardBillboardsIndexRoute: DashboardBillboardsIndexRoute,
  DashboardBlogsIndexRoute: DashboardBlogsIndexRoute,
  DashboardImagesIndexRoute: DashboardImagesIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardQuotesIndexRoute: DashboardQuotesIndexRoute,
  DashboardSkillsIndexRoute: DashboardSkillsIndexRoute,
  DashboardSocialsIndexRoute: DashboardSocialsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DeleteMyDataRoute: DeleteMyDataRoute,
  LoginRoute: LoginRoute,
  SocialsRoute: SocialsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ImagesKeyRoute: ImagesKeyRoute,
  LegalSlugRoute: LegalSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PortfolioProjectIdIndexRoute: PortfolioProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
